from django.db import models

class SentenceTable(models.Model):
    repo=models.CharField(max_length=50)
    project=models.CharField(max_length=50)
    issue_number = models.PositiveIntegerField()
    originaltext=models.TextField()
    processedtext=models.TextField()
    full_length= models.PositiveIntegerField()
    length = models.PositiveIntegerField()
    tloc= models.FloatField()
    cloc= models.FloatField()
    tpos1= models.FloatField()
    tpos2= models.FloatField()
    clen= models.FloatField()
    tlen= models.FloatField()
    ppau= models.FloatField()
    npau= models.FloatField()
    has_code=models.BooleanField()
    first_turn=models.BooleanField()
    last_turn=models.BooleanField()
    begauth=models.BooleanField()
    aa=models.CharField(max_length=20)
    isclosed=models.BooleanField()
    code=models.CharField(max_length=30)
    created_at=models.BigIntegerField()
    
